### ISSUE TITLE
Wrong class in the SpringApplication.run method

### ISSUE THREAD

**Issue by deepres** [spring-guides/gs-consuming-web-service#11]
I hope I understood your guide correctly:

"The main() method defers to the SpringApplication helper class, providing WeatherConfiguration.class as an argument to its run() method." 

 and there should be:

public static void main(String[] args) {
    SpringApplication.run(WeatherConfiguration.class);
}

instead of Application.class

**Comment by dsyer** [comment]
No that is incorrect. `Application` has `@SpringBootApplication` on it so that's the one we want to run.
