### ISSUE TITLE
report!

### ISSUE THREAD

**Issue by lakeoffaith** [spring-guides/gs-consuming-web-service#12]
Could not retrieve the last modification timestamp for the URI 
http://wsf.cdyne.com/WeatherWS/Weather.asmx?wsdl  
how can i solve this problem? is this url can't work? but i can get .wsdl from the url.

**Comment by dsyer** [comment]
What exactly is the problem then? Does it stop the project from building or running? What are your steps to repeat and what do you observe, and why is it wrong?

**Comment by lakeoffaith** [comment]
step one: i check out the gs-consuming-web-service-master;
step two: into  gs-consuming-web-service-master\complete
step three: mvn spring-boot:run              

D:\javatools\workspace\gs-consuming-web-service-master\complete>mvn spring-boot:
run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-consuming-web-service 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.2.7.RELEASE:run (default-cli) > test-compi
le @ gs-consuming-web-service >>>
[INFO]
[INFO] --- maven-jaxb2-plugin:0.12.3:generate (default) @ gs-consuming-web-servi
ce ---
[INFO] Up-to-date check for source resources [[http://wsf.cdyne.com/WeatherWS/We
ather.asmx?wsdl, file:/D:/javatools/workspace/gs-consuming-web-service-master/co
mplete/pom.xml]] and taret resources [[]].
[WARNING] The URI [http://wsf.cdyne.com/WeatherWS/Weather.asmx?wsdl] seems to re
present an absolute HTTP or HTTPS URL. Getting the last modification timestamp i
s only possible if the URL is accessible and if the server returns the [Last-Mod
ified] header correctly. This method is not reliable and is likely to fail. In t
his case the last modification timestamp will be assumed to be unknown.
[ERROR] Could not retrieve the last modification timestamp for the URI [http://w
sf.cdyne.com/WeatherWS/Weather.asmx?wsdl] from the HTTP URL connection. The [Las
t-Modified] header was probably not set correctly.
[WARNING] Last modification of the URI [http://wsf.cdyne.com/WeatherWS/Weather.a
smx?wsdl] is not known.
[INFO] Sources are not up-to-date, XJC will be executed.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gs-consumi
ng-web-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gs-consuming-we
b-service ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to D:\javatools\workspace\gs-consuming-web-serv
ice-master\complete\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gs
-consuming-web-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\javatools\workspace\gs-consuming-w
eb-service-master\complete\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gs-cons
uming-web-service ---
[INFO] No sources to compile
[INFO]
[INFO] <<< spring-boot-maven-plugin:1.2.7.RELEASE:run (default-cli) < test-compi
le @ gs-consuming-web-service <<<
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.7.RELEASE:run (default-cli) @ gs-consumi
ng-web-service ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.7.RELEASE)

2015-10-23 16:15:56.566  INFO 9168 --- [lication.main()] hello.Application
                  : Starting Application on lizhengang with PID 9168 (D:\javatoo
ls\workspace\gs-consuming-web-service-master\complete\target\classes started by
zhengang in D:\javatools\workspace\gs-consuming-web-service-master\complete)
2015-10-23 16:15:56.607  INFO 9168 --- [lication.main()] s.c.a.AnnotationConfigA
pplicationContext : Refreshing org.springframework.context.annotation.Annotation
ConfigApplicationContext@48417991: startup date [Fri Oct 23 16:15:56 CST 2015];
root of context hierarchy
2015-10-23 16:15:57.291  INFO 9168 --- [lication.main()] o.s.oxm.jaxb.Jaxb2Marsh
aller             : Creating JAXBContext with context path [hello.wsdl]
2015-10-23 16:15:57.572  INFO 9168 --- [lication.main()] o.s.ws.soap.saaj.SaajSo
apMessageFactory  : Creating SAAJ 1.3 MessageFactory with SOAP 1.1 Protocol
2015-10-23 16:15:57.577 DEBUG 9168 --- [lication.main()] o.s.ws.soap.saaj.SaajSo
apMessageFactory  : Using MessageFactory class [com.sun.xml.internal.messaging.s
aaj.soap.ver1_1.SOAPMessageFactory1_1Impl]
2015-10-23 16:15:57.963  INFO 9168 --- [lication.main()] o.s.j.e.a.AnnotationMBe
anExporter        : Registering beans for JMX exposure on startup
2015-10-23 16:15:57.973  INFO 9168 --- [lication.main()] hello.WeatherClient
                  : Requesting forecast for 94304
2015-10-23 16:15:57.980 DEBUG 9168 --- [lication.main()] o.s.ws.client.core.WebS
erviceTemplate    : Opening [org.springframework.ws.transport.http.HttpUrlConnec
tion@44e5e4fd] to [http://wsf.cdyne.com/WeatherWS/Weather.asmx]
2015-10-23 16:15:58.025 DEBUG 9168 --- [lication.main()] o.s.ws.client.MessageTr
acing.sent        : Sent request [SaajSoapMessage {http://ws.cdyne.com/WeatherWS
/}GetCityForecastByZIP]
2015-10-23 16:15:59.141 DEBUG 9168 --- [lication.main()] o.s.ws.client.MessageTr
acing.received    : Received response [SaajSoapMessage {http://ws.cdyne.com/Weat
herWS/}GetCityForecastByZIPResponse] for request [SaajSoapMessage {http://ws.cdy
ne.com/WeatherWS/}GetCityForecastByZIP]
2015-10-23 16:15:59.168  INFO 9168 --- [lication.main()] hello.Application
                  : Started Application in 2.994 seconds (JVM running for 11.649
)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.306 s
[INFO] Finished at: 2015-10-23T16:15:59+08:00
[INFO] Final Memory: 29M/221M
[INFO] ------------------------------------------------------------------------
2015-10-23 16:15:59.449  INFO 9168 --- [       Thread-1] s.c.a.AnnotationConfigA
pplicationContext : Closing org.springframework.context.annotation.AnnotationCon
figApplicationContext@48417991: startup date [Fri Oct 23 16:15:56 CST 2015]; roo
t of context hierarchy
2015-10-23 16:15:59.451  INFO 9168 --- [       Thread-1] o.s.j.e.a.AnnotationMBe
anExporter        : Unregistering JMX-exposed beans on shutdown

D:\javatools\workspace\gs-consuming-web-service-master\complete>s

**Comment by dsyer** [comment]
Seems to be working? What's the problem?

**Comment by lakeoffaith** [comment]
what? why i can't get the result ,the weather is not printed.

**Comment by dsyer** [comment]
I don't see anywhere in the code path that prints the weather (which is odd I admit, but I don't think it's broken).

**Comment by lakeoffaith** [comment]
URL has a problem it is?if i change the url ,can it work well ? i even don't understand return args-> ...(which in Application.java )

**Comment by dsyer** [comment]
The bulk of `Application.java` is a `@Bean` definition which returns a `CommandLineRunner` (defined as a Lambda). It's working as designed. I don't know what you mean, sorry.

**Comment by lakeoffaith** [comment]
@Bean
	CommandLineRunner lookup(WeatherClient weatherClient) {
		return args -> {
			String zipCode = "94304";

			if (args.length > 0) {
				zipCode = args[0];
			}
			GetCityForecastByZIPResponse response = weatherClient.getCityForecastByZip(zipCode);
		};
	}
 return  args ->    i can't understand.

**Comment by dsyer** [comment]
It's a `CommandLineRunner` (interface defined in Spring Boot). It gets run on startup (per the docs). The syntax is a Java 8 Lambda (google it if you never saw one before).

**Comment by lakeoffaith** [comment]
thank you ,i only over the wall to get the google ,Chinese-British friendship forever

**Comment by draconk** [comment]
to get it to print you need to modify the lookup method just after getting the response so it ends like this

@Bean
	CommandLineRunner lookup(WeatherClient weatherClient) {	
			return args -> {
			String zipCode = "94304";

			if (args.length > 0) {
				zipCode = args[0];
			}
			GetCityForecastByZIPResponse response = weatherClient.getCityForecastByZip(zipCode);
			weatherClient.printResponse(response);
		};
	}

**Comment by gregturn** [comment]
See https://github.com/spring-guides/gs-consuming-web-service/issues/9 regarding issues with the weather service.

**Comment by draconk** [comment]
right now and yesterday when I did the guide for the first time the weather service worked great for me what didn't work was the printing issue that I said how to fix on my last comment

**Comment by lakeoffaith** [comment]
it work well ,thank you
