### ISSUE TITLE
Build failure weather service

### ISSUE THREAD

**Issue by pmesgari** [spring-guides/gs-consuming-web-service#14]
![weatherfail](https://cloud.githubusercontent.com/assets/14719521/14679156/facf33b4-0718-11e6-9ca9-361df45f35b7.PNG)
I followed the tutorial using Maven from command line on Windows. The build fails due to timestamp errors.

**Comment by gregturn** [comment]
There is an outstanding issue with the SOAP-based service this guide is built on no longer working as expected. You can track it in #9.
