### ISSUE TITLE
Build failure with JDK 1.8.0_91-b14

### ISSUE THREAD

**Issue by lbndev** [spring-guides/gs-consuming-web-service#15]
Following the tutorial on my machine (STS, JDK 1.8.0_91-b14, windows) fails with :

> [INFO] --- maven-jaxb2-plugin:0.12.3:generate (default) @ gs-consuming-web-service ---
> [WARNING] The POM for org.glassfish.jaxb:jaxb-runtime:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
> [WARNING] The POM for org.glassfish.jaxb:jaxb-xjc:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
> [WARNING] Error injecting: org.jvnet.mjiip.v_2.XJC2Mojo
> java.lang.NoClassDefFoundError: com/sun/xml/bind/api/ErrorListener
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(Unknown Source)
>   at java.security.SecureClassLoader.defineClass(Unknown Source)
>   at java.net.URLClassLoader.defineClass(Unknown Source)
> (... snip ...)
> Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.api.ErrorListener
>   at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
>   at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
>   at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
>   at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)

Upgrading the maven-jaxb2-plugin to latest version and adding jaxb dependencies fixes the issue :

```
    <plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb2-plugin</artifactId>
                <version>0.13.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <schemaLanguage>WSDL</schemaLanguage>
                    <generatePackage>hello.wsdl</generatePackage>
                    <schemas>
                        <schema>
                            <url>http://wsf.cdyne.com/WeatherWS/Weather.asmx?wsdl</url>
                        </schema>
                    </schemas>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                        <version>2.2.11</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-xjc</artifactId>
                        <version>2.2.11</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-core</artifactId>
                        <version>2.2.11</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by dsyer** [comment]
Both versions of the plugin work for me from the command line and I don't need any of those additional `com.sun.*` dependencies. Can you verify that works for you too?

**Comment by fedy2** [comment]
Same problem here.

**Comment by dsyer** [comment]
Please re-check the version of Java that you are using. Ask Maven to tell you what version it is using too.

**Comment by fedy2** [comment]
I've solved adding the following dependency to the plugin:

					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-osgi</artifactId>
						<version>2.2.11</version>
					</dependency>

Therefore the plugin declaration become:

<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.13.1</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<schemaLanguage>WSDL</schemaLanguage>
					<generatePackage>hello.wsdl</generatePackage>
					<schemas>
						<schema>
							<url>http://wsf.cdyne.com/WeatherWS/Weather.asmx?wsdl</url>
						</schema>
					</schemas>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-osgi</artifactId>
						<version>2.2.11</version>
					</dependency>
				</dependencies>
			</plugin>

**Comment by dsyer** [comment]
Those classes are in the JDK (since 1.5 I think). So you shouldn't need to do this, and we won't be making any changes to the guide. I guess your JDK is foobar.

**Comment by jiz5163** [comment]
After following fedy2's example I get another error on the execution 

`Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed. (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:
 0.13.1:generate:default:generate-sources) org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.jvnet.jaxb2.maven2:maven-
 jaxb2-plugin:0.13.1:generate failed. at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331) at org.eclipse.m2e.core.internal.embedder.MavenImpl
 $11.call(MavenImpl.java:1362) at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360) at `

If I remove <goal> generate </goal> 
error disappears. How can I keep generate goal, so it would generate the files for me.

**Comment by EAAR** [comment]
I have the same issue, here the JDK version 
 C:\Users\EAARW7>mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: M:\SPRING\apache-maven-3.3.9\bin\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: M:\Program Files\Java\jdk1.8.0_121\jre
Default locale: es_MX, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by dsyer** [comment]
Still works for me. Please attach the output from "mvn spring-boot:run -X".

**Comment by apupier** [comment]
Hello @EAAR 

it seems that your JAVA_HOME is pointing to a JRE and not to a JDK

M:\Program Files\Java\jdk1.8.0_121\jre

should be replaced by

M:\Program Files\Java\jdk1.8.0_121

**Comment by rmundkowsky** [comment]
Thanks @apupier 

I JDK for Eclipse set correctly for the INSTALLED JREs, so it was compiling the pom.xml in Eclipse fine. But when I ran Ant from Eclipse it was picking up the JRE that was in the PATH from where Eclipse was launched. I added JAVA_HOME to OS System ENVs and %JAVA_HOME%\bin to the front of the PATH and that fixed it.  Wow, otherwise I would have been playing with dependencies thinking one of them had changed.

**Comment by golonzovsky** [comment]
you might need to add plugin dependency if using with java 11
```
				<dependencies>
					<dependency>
						<groupId>org.glassfish.jaxb</groupId>
						<artifactId>jaxb-runtime</artifactId>
						<version>2.3.1</version>
					</dependency>
				</dependencies>
			</plugin>
			<!-- end::wsdl[] -->
		</plugins>
	</build>
```
