### ISSUE TITLE
Issues consuming-web-service on cloudfoundry

### ISSUE THREAD

**Issue by kweheliye** [spring-guides/gs-consuming-web-service#17]
I followed your example to send and receive messages, my application works perfectly on local machine (localhost:8080) ,  but when I upload the application on cloudfoundry I get  null pointer exception when i try to access response object.
please see attached logs [log.txt](https://github.com/spring-guides/gs-consuming-web-service/files/634080/log.txt)

Have you test it on cloudfoundry ?

**Comment by dsyer** [comment]
The sample in this guide is not a web app so it isn't supposed to run in Cloud Foundry. Probably you were running something a bit different in that case?

**Comment by kweheliye** [comment]
Yes. You right. Thanks for pointing out.

**Comment by kweheliye** [comment]
Hi Dave, 
Can we run Spring-WS Client in Cloud Foundry ?

**Comment by dsyer** [comment]
Why would you not be able to?

**Comment by kweheliye** [comment]
With large data, the response object is returned while message are still coming. please see the second line of the log file.
[log.txt](https://github.com/spring-guides/gs-consuming-web-service/files/642313/log.txt)

**Comment by gregturn** [comment]
CF requires a server up and running. The guide is more like a job that runs and shuts down. Hence, CF looks at it like a failure. 

If you built a server app that made SOAP calls, it would run just fine since it's simply a web call.

**Comment by kweheliye** [comment]
Thanks @gregturn

**Comment by kweheliye** [comment]
Hi Greg,

It runs fine with EC2 + WildFly.

**Comment by gregturn** [comment]
:)
