### ISSUE TITLE
Binding files, conflicts

### ISSUE THREAD

**Issue by AMetnik** [spring-guides/gs-consuming-web-service#19]
Hey, is it possible to get an updated guide that also includes if property and element has the same name in a complextype ?

Basicly how to use binding files in this current setup.

**Comment by gregturn** [comment]
Can you elaborate?

**Comment by AMetnik** [comment]
Yes thanks for replying

I'm using your guide, and it seems very nice, and all worked nicely with your SOAP.
But my target is a much more "advanced" SOAP, and amongst others they have this complextype:
(you can obtain their wsdl [here:]( https://uat.ws2.rki.dk/person.asmx?wsdl) )
> <s:complexType name="AdresseData">
>         <s:complexContent mixed="false">
>           <s:extension base="s1:XmlData">
>             <s:sequence>
>               <s:element minOccurs="0" maxOccurs="1" name="CoNavn" type="s1:NavnData" />
>               <s:element minOccurs="0" maxOccurs="1" name="PostDistrikt" type="s1:PostDistriktData" />
>               <s:element minOccurs="0" maxOccurs="1" name="Kommune" type="s1:KommuneData" />
>               <s:element minOccurs="0" maxOccurs="1" name="HusNr" type="s1:HusNrData" />
>               <s:element minOccurs="0" maxOccurs="1" name="Land" type="s1:LandData" />
>               <s:element minOccurs="0" maxOccurs="1" name="Bynavn" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="Vej" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="BygningNr" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="Etage" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="SideDoer" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="PostBox" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="Udenlandsk" type="s1:ArrayOfString" />
>               <s:element minOccurs="0" maxOccurs="1" name="AdresseLinier" type="s1:ArrayOfString" />
>               <s:element minOccurs="0" maxOccurs="1" name="Dato" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="ReklameBeskyttet" type="s:string" />
>               <s:element minOccurs="0" maxOccurs="1" name="ReklameBeskyttetFra" type="s:string" />
>             </s:sequence>
>             <s:attribute name="udenlandsk" type="s:string" />
>             <s:attribute name="beskyttetFra" type="s:string" />
>             <s:attribute name="beskyttet" type="s:string" />
>             <s:attribute name="VejNr" type="s:string" />
>             <s:attribute name="SogeVejNr" type="s:string" />
>           </s:extension>
>         </s:complexContent>
>       </s:complexType>

Which has both a an s:attribute and s:element by the name Udenlandsk, which is perfectly ok in xml, but Jaxb will translate these into the same named property, unless we somehow use a binding file as well, I just can't figure out how.

So I looked around, and seems this way to do things is "deprecated" and there is now a new way to do it, https://github.com/jacobono/gradle-jaxb-plugin though i cannot get that to work neither :-(

Would you like more information?

**Comment by dsyer** [comment]
It's not really a problem with the guide, or even with Spring, then is it? You should look to StackOverflow for general JAXB usage questions.

**Comment by AMetnik** [comment]
@dsyer That you are completely correct in, that it is not really a "problem" with the guide.

Merely a suggestion for improvement, apologizes if it was not clear for the get go.

Though believe me, I've looked a stackoverflow. But I'm reading and reading, but thanks anyways. 
-eod
