### ISSUE TITLE
Not able to fetch WSDL

### ISSUE THREAD

**Issue by vikaskotnala** [spring-guides/gs-consuming-web-service#20]
Following URL "http://www.webservicex.com/stockquote.asmx?WSDL" is giving Error: 

`"The current identity (NT AUTHORITY\NETWORK SERVICE) does not have write access to 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files'."`

**Comment by dsyer** [comment]
Grrr. It is becoming harder and harder to find any public APIs that offer SOAP-based endpoints (everyone switched to JSON). This one is flakey, it seems, so maybe we'll have to write our own. Pull requests welcome, if anyone can find one that works reliably.

**Comment by dsyer** [comment]
Works for me now. Maybe a temporary glitch.
