### ISSUE TITLE
Missing arg-parameter in main method of Application

### ISSUE THREAD

**Issue by ma501** [spring-guides/gs-consuming-web-service#24]
There is a bug in the main method of Application class
`public static void main(String[] args) {
    SpringApplication.run(Application.class);
}`
should be 
`public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
}`
Otherwise the command line arguments are not passed to the lookup method.

**Comment by gregturn** [comment]
Pull requests welcome!

**Comment by ma501** [comment]
My first ever pull request has been created (#25).

**Comment by dsyer** [comment]
Closed via #25
