### ISSUE TITLE
Using own wsdl fails

### ISSUE THREAD

**Issue by jegjessing** [spring-guides/gs-consuming-web-service#28]
I'm trying to change the WSDL to use my own, but no classes are generated :-1: 
It only makes the .episode and that is it.
I can generate all the classes and java files using wsimport, but I'm not sure combining wsimport and this project is a good idea.

Any idea why no classes/java are generated?
(I'm sure you need more info :-))
Thanks in advance

**Comment by dsyer** [comment]
> I'm sure you need more info

Indeed. How did you provide your own WSDL? Is it compatible with the one used in the guide? What happened when you build (logs, exceptions, etc.)?

**Comment by dsyer** [comment]
No feedback. Closing.
