### ISSUE TITLE
Doesn't generate hello package with maven

### ISSUE THREAD

**Issue by yhjhoo** [spring-guides/gs-consuming-web-service#30]
$ mvn clean compile

Just hang there and nothing was generated.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-consuming-web-service 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-jaxb2-plugin:0.12.3:generate (default) @ gs-consuming-web-service ---
[INFO] Up-to-date check for source resources [[http://www.webservicex.com/stockquote.asmx?WSDL, file:/Users/huajieyang/github/gs-consuming-web-service/initial/pom.xml]] and taret resources [[]].
[WARNING] The URI [http://www.webservicex.com/stockquote.asmx?WSDL] seems to represent an absolute HTTP or HTTPS URL. Getting the last modification timestamp is only possible if the URL is accessible and if the server returns the [Last-Modified] header correctly. This method is not reliable and is likely to fail. In this case the last modification timestamp will be assumed to be unknown.

**Comment by alexanderfournier** [comment]
@yhjhoo you ever get this?

**Comment by gregturn** [comment]
Duplicates #27

**Comment by houssam-eldeen** [comment]
what's the right URL please?
or 
could you send the right WSDL file?

thanks
