### ISSUE TITLE
Incorrect step (Make the application executable) in the guide

### ISSUE THREAD

**Issue by viswatmula** [spring-guides/gs-consuming-web-service#39]
1. The step says CountryConfiguration.class is passed as an argument to the run() method 
but the code is passing Application.class as argument to the run method.

2. lookup method parameter type is CountryClient but the parameter is named as quoteClient

3. The paragraph "This application is hard coded to look up symbol 'MSFT' which correspond to Microsoft Corporation. Towards the end of this guide, you’ll see how to plug in a different symbol without editing the code." does not belong to this guide.

**Comment by dsyer** [comment]
I think the guide was cleaned up a while ago to remove references to the old domain (quotes).
