### ISSUE TITLE
Documentation links

### ISSUE THREAD

**Issue by paulshelestovich** [spring-guides/gs-consuming-web-service#51]
The links to code examples are not displayed correctly in the Readme and the original article (https://spring.io/guides/gs/consuming-web-service/#scratch). For example:

> The following listing shows the pom.xml file that is created when you choose Maven:

> link:initial/pom.xml[]
The following listing shows the build.gradle file that is created when you choose Gradle:

> link:initial/build.gradle[]

**Comment by dsyer** [comment]
Stale cache I think. Try again now.

**Comment by paulshelestovich** [comment]
Works in the article now, but still broken in the readme:

![image](https://user-images.githubusercontent.com/2280657/102753706-abd42e00-43d0-11eb-89ec-5d8dfa2fb860.png)

**Comment by dsyer** [comment]
That’s working as designed then (the README is the source code for the website).
