### ISSUE TITLE
java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory

### ISSUE THREAD

**Issue by bitsofinfo** [spring-guides/gs-consuming-web-service#58]
Trying to use the example in a existing spring project (spring 3.x) getting

```
* What went wrong:
Execution failed for task ':genJaxb'.
> java.lang.AssertionError: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
   - with linked exception:
  [java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory]
```

**Comment by nander25** [comment]
I was running into the same issue. In my build.gradle.kts, what fixed it was adding `jakarta.xml.bind:jakarta.xml.bind-api` and`com.sun.xml.bind:jaxb-impl` to my jaxb configuration. That way they gets added to the classpath when running the xjc ant task. The result was:
```
val jaxb by configurations.creating

dependencies {
    jaxb("com.sun.xml.bind:jaxb-xjc:$jaxb-version")
    jaxb("jakarta.xml.bind:jakarta.xml.bind-api")
    jaxb("com.sun.xml.bind:jaxb-impl:$jaxb-version")
}
```

**Comment by Buzzardo** [comment]
We plan to rewrite this guide and already have an issue to remind us about the JAXB issues, so I'll close this one.

See https://github.com/spring-guides/gs-consuming-web-service/issues/54
