### ISSUE TITLE
Old parameter name in the CommandLineRunner

### ISSUE THREAD

**Issue by krios2146** [spring-guides/gs-consuming-web-service#61]
In the previous version of the guide, there was a `QuoteClient`, and the name of the parameter hasn't been changed. 

Using `quoteClient` for a `CountryClient` may be confusing.

https://github.com/spring-guides/gs-consuming-web-service/blob/72c321cce6672c8956a43cf90136f720d0a3cb2b/complete/src/main/java/com/example/consumingwebservice/ConsumingWebServiceApplication.java#L18-L29

**Comment by Buzzardo** [comment]
This is a good first issue for someone who would like to get started with contributing to Spring. To do it, change `quoteClient` to `countryClient`.
