### ISSUE TITLE
Package wsdl doesn't exist

### ISSUE THREAD

**Issue by MitVo** [spring-guides/gs-consuming-web-service#8]
this imports are in WeatherClient but there's no package or something to locate:
import hello.wsdl.Forecast;
import hello.wsdl.ForecastReturn;
import hello.wsdl.GetCityForecastByZIP;
import hello.wsdl.GetCityForecastByZIPResponse;
import hello.wsdl.Temp;

**Comment by dsyer** [comment]
Works for me:

```
$ cd complete
$ mvn clean package
$ find target/generated-sources/
target/generated-sources/
target/generated-sources/annotations
target/generated-sources/xjc
target/generated-sources/xjc/hello
target/generated-sources/xjc/hello/wsdl
target/generated-sources/xjc/hello/wsdl/POP.java
target/generated-sources/xjc/hello/wsdl/GetWeatherInformationResponse.java
target/generated-sources/xjc/hello/wsdl/package-info.java
target/generated-sources/xjc/hello/wsdl/Forecast.java
target/generated-sources/xjc/hello/wsdl/Temp.java
target/generated-sources/xjc/hello/wsdl/GetCityWeatherByZIP.java
target/generated-sources/xjc/hello/wsdl/WeatherDescription.java
target/generated-sources/xjc/hello/wsdl/GetWeatherInformation.java
target/generated-sources/xjc/hello/wsdl/GetCityWeatherByZIPResponse.java
target/generated-sources/xjc/hello/wsdl/GetCityForecastByZIPResponse.java
target/generated-sources/xjc/hello/wsdl/ArrayOfWeatherDescription.java
target/generated-sources/xjc/hello/wsdl/WeatherReturn.java
target/generated-sources/xjc/hello/wsdl/GetCityForecastByZIP.java
target/generated-sources/xjc/hello/wsdl/ForecastReturn.java
target/generated-sources/xjc/hello/wsdl/ArrayOfForecast.java
target/generated-sources/xjc/hello/wsdl/ObjectFactory.java
target/generated-sources/xjc/META-INF
target/generated-sources/xjc/META-INF/sun-jaxb.episode
```

**Comment by gregturn** [comment]
They are generated in the build, driven by the contract.

https://github.com/spring-guides/gs-consuming-web-service/blob/master/complete/pom.xml#L38-L60

**Comment by gregturn** [comment]
There is also a gradle plugin to do the same.

**Comment by houssam-eldeen** [comment]
please, could you simply told me in steps how to handle that exception:
Exception: java.io.FileNotFoundException: http://www.webservicex.com/stockquote.asmx?WSDL.

**Comment by dsyer** [comment]
That’s a different problem. There’s no workaround. You just have to use a different URL if that one doesn’t exist.

**Comment by houssam-eldeen** [comment]
Thanks Dsyer
could you please tell me what's the right URL ??

**Comment by gregturn** [comment]
What we're saying is that when this guide was authored, the URL above was a freely hosted weather service. They have since taken it down, and we have yet to find another suitable demo-friendly URL.

If I can ever find time, I might need to craft a Pivotal-hosted demo service.

**Comment by dsyer** [comment]
@gregturn I converted this guide to use a local service. The instructions are fairly clear I think, but we can always add more.
